# Generated by Django 4.2

from django.conf import settings  # настройки проекта (включая модель пользователя)
from django.db import migrations, models  # инструменты для миграций и моделей
import django.db.models.deletion  # поведение при удалении (CASCADE и др.)


class Migration(migrations.Migration):

    initial = True  # это первая миграция (создание таблиц)

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        # зависимость от модели пользователя (User)
    ]

    operations = [

        # -------------------------------
        # МОДЕЛЬ Course (Курс)
        # -------------------------------
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                # уникальный ID

                ('title', models.CharField(max_length=200, verbose_name='Название')),
                # название курса

                ('slug', models.SlugField(unique=True, verbose_name='URL')),
                # уникальный адрес курса (например: html-basics)

                ('description', models.TextField(blank=True, verbose_name='Описание')),
                # описание курса

                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                # порядок отображения

                ('icon', models.CharField(blank=True, default='book', max_length=50, verbose_name='Иконка')),
                # иконка (например emoji или класс)

                ('created_at', models.DateTimeField(auto_now_add=True)),
                # дата создания
            ],
            options={
                'verbose_name': 'Курс',
                'verbose_name_plural': 'Курсы',
                'ordering': ['order'],  # сортировка по порядку
            },
        ),

        # -------------------------------
        # МОДЕЛЬ Lesson (Урок)
        # -------------------------------
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(primary_key=True)),

                ('title', models.CharField(max_length=200, verbose_name='Название')),
                # название урока

                ('slug', models.SlugField(verbose_name='URL')),
                # URL урока

                ('content', models.TextField(verbose_name='Содержание')),
                # текст урока (HTML контент)

                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                # порядок урока

                ('created_at', models.DateTimeField(auto_now_add=True)),
                # дата создания

                ('course', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE,
                    related_name='lessons',
                    to='courses.course'
                )),
                # связь с курсом (один курс → много уроков)
            ],
            options={
                'verbose_name': 'Урок',
                'verbose_name_plural': 'Уроки',
                'ordering': ['order'],
                'unique_together': {('course', 'slug')},
                # в одном курсе slug должен быть уникальным
            },
        ),

        # -------------------------------
        # МОДЕЛЬ Assignment (Задание)
        # -------------------------------
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.BigAutoField(primary_key=True)),

                ('title', models.CharField(max_length=200, verbose_name='Название')),
                # название задания

                ('description', models.TextField(verbose_name='Описание')),
                # описание задания

                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                # порядок

                ('created_at', models.DateTimeField(auto_now_add=True)),
                # дата создания

                ('lesson', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE,
                    related_name='assignments',
                    to='courses.lesson'
                )),
                # связь с уроком (один урок → много заданий)
            ],
            options={
                'verbose_name': 'Задание',
                'verbose_name_plural': 'Задания',
                'ordering': ['order'],
            },
        ),

        # -------------------------------
        # МОДЕЛЬ Submission (Работа ученика)
        # -------------------------------
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.BigAutoField(primary_key=True)),

                ('code', models.TextField(blank=True, verbose_name='Код')),
                # код, который отправил ученик

                ('comment', models.TextField(blank=True, verbose_name='Комментарий ученика')),
                # комментарий ученика

                ('status', models.CharField(
                    choices=[
                        ('pending', 'На проверке'),
                        ('accepted', 'Принято'),
                        ('revision', 'Нужно доработать')
                    ],
                    default='pending',
                    max_length=20,
                    verbose_name='Статус'
                )),
                # статус проверки

                ('reviewer_comment', models.TextField(blank=True, verbose_name='Комментарий проверяющего')),
                # комментарий учителя

                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                # дата проверки

                ('created_at', models.DateTimeField(auto_now_add=True)),
                # дата отправки

                ('assignment', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE,
                    related_name='submissions',
                    to='courses.assignment'
                )),
                # связь с заданием

                ('user', models.ForeignKey(
                    blank=True,
                    null=True,
                    on_delete=django.db.models.deletion.CASCADE,
                    related_name='submissions',
                    to=settings.AUTH_USER_MODEL
                )),
                # пользователь (ученик)
            ],
            options={
                'verbose_name': 'Работа',
                'verbose_name_plural': 'Работы',
            },
        ),
    ]